### ISSUE TITLE
Add Mirror Toggle for Tensionboards

### ISSUE THREAD

**Issue by gardaholm** [marcodejongh/boardsesh#16]
For Tension Boards a Mirror Toggle would be great. 
Easiest way is probably inside the queue list, next to the Forward and Backward Buttons.

This mirror state should also be used when ticking the climbs.

**Comment by gardaholm** [comment]
mirroring works in the interface, but the leds on the board stay in the original position, they don't swap.

**Comment by marcodejongh** [comment]
Ah oops let me fix that
