### ISSUE TITLE
Use led_color instead of screen_color to light up a climb

### ISSUE THREAD

**Issue by gardaholm** [marcodejongh/boardsesh#20]
tension (maybe kilter too?) uses different colors for led and screen. they are marked in the database. 
right now it seems that the screen colors are used for the leds and this messes up the colors. With this values blue and pink looks almost identical.

<img width="934" alt="image" src="https://github.com/user-attachments/assets/297d6188-cabf-4056-8b0e-c901a5730483">

**Comment by marcodejongh** [comment]
I think for kilter they are the same, climbdex actually has a bug in the Bluetooth code that might the colours slightly off for kilter.

but changes these colours to the board colours should be easy. So the screen_colors are what is shown in the app?

**Comment by gardaholm** [comment]
Exactly. Think we had a similar issue on climbdex, after switching to the led_colors for the Bluetooth the colors were correctly. 

I think kilter uses orange for footholds (?) this is probably probably a better choice then the pink on the tension board.
