### ISSUE TITLE
Add UI indication if Route is Added to Queue

### ISSUE THREAD

**Issue by gardaholm** [marcodejongh/boardsesh#70]
Right now you don't get and indication if you successfully added a route. 
This can result in multiple adds of the same route from one person. 

A notification Banner after clicking the (+) Icon would be helpful. 
Or a check that one route can't be added twice into the queue (but this would prevent creating circuits) …

**Comment by marcodejongh** [comment]
@gardaholm is this one closer now that #86 is done? Or is there more needed?

**Comment by gardaholm** [comment]
Is done in my opinion.
